
package com.chargepartner.hubject.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "eRoamingAuthenticationDataPortType", targetNamespace = "http://www.hubject.com/b2b/services/authenticationdata/v2.0")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ERoamingAuthenticationDataPortType {


    /**
     * 
     * @param result
     * @param actionType
     * @param providerAuthenticationData
     * @param sessionID
     * @param partnerSessionID
     * @param statusCode
     */
    @WebMethod(action = "eRoamingPushAuthenticationData")
    @RequestWrapper(localName = "eRoamingPushAuthenticationData", targetNamespace = "http://www.hubject.com/b2b/services/authenticationdata/v2.0", className = "com.chargepartner.hubject.ws.ERoamingPushAuthenticationData")
    @ResponseWrapper(localName = "eRoamingAcknowledgement", targetNamespace = "http://www.hubject.com/b2b/services/commontypes/v2.0", className = "com.chargepartner.hubject.ws.ERoamingAcknowledgement")
    public void eRoamingPushAuthenticationData(
        @WebParam(name = "ActionType", targetNamespace = "http://www.hubject.com/b2b/services/authenticationdata/v2.0")
        String actionType,
        @WebParam(name = "ProviderAuthenticationData", targetNamespace = "http://www.hubject.com/b2b/services/authenticationdata/v2.0")
        ProviderAuthenticationDataType providerAuthenticationData,
        @WebParam(name = "Result", targetNamespace = "http://www.hubject.com/b2b/services/commontypes/v2.0", mode = WebParam.Mode.OUT)
        Holder<Boolean> result,
        @WebParam(name = "StatusCode", targetNamespace = "http://www.hubject.com/b2b/services/commontypes/v2.0", mode = WebParam.Mode.OUT)
        Holder<StatusCodeType> statusCode,
        @WebParam(name = "SessionID", targetNamespace = "http://www.hubject.com/b2b/services/commontypes/v2.0", mode = WebParam.Mode.OUT)
        Holder<String> sessionID,
        @WebParam(name = "PartnerSessionID", targetNamespace = "http://www.hubject.com/b2b/services/commontypes/v2.0", mode = WebParam.Mode.OUT)
        Holder<String> partnerSessionID);

    /**
     * 
     * @param authenticationData
     * @param operatorID
     * @param statusCode
     */
    @WebMethod(action = "eRoamingPullAuthenticationData")
    @RequestWrapper(localName = "eRoamingPullAuthenticationData", targetNamespace = "http://www.hubject.com/b2b/services/authenticationdata/v2.0", className = "com.chargepartner.hubject.ws.ERoamingPullAuthenticationData")
    @ResponseWrapper(localName = "eRoamingAuthenticationData", targetNamespace = "http://www.hubject.com/b2b/services/authenticationdata/v2.0", className = "com.chargepartner.hubject.ws.ERoamingAuthenticationData")
    public void eRoamingPullAuthenticationData(
        @WebParam(name = "OperatorID", targetNamespace = "http://www.hubject.com/b2b/services/authenticationdata/v2.0")
        String operatorID,
        @WebParam(name = "AuthenticationData", targetNamespace = "http://www.hubject.com/b2b/services/authenticationdata/v2.0", mode = WebParam.Mode.OUT)
        Holder<com.chargepartner.hubject.ws.ERoamingAuthenticationData.AuthenticationData> authenticationData,
        @WebParam(name = "StatusCode", targetNamespace = "http://www.hubject.com/b2b/services/authenticationdata/v2.0", mode = WebParam.Mode.OUT)
        Holder<StatusCodeType> statusCode);

}
